version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mudar@123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: pedrovcorsino/tech_challenge:pontomenos
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mudar@123
      POSTGRES_DB: postgres
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

volumes:
  postgres_data:
